services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: python manage.py runserver

volumes:
  web-django:
  web-static: